### ISSUE TITLE
Ticket Tracking API

### ISSUE THREAD

**Issue by dr4hcu5-jan** [unikino-gegenlicht/cmp-backend#1]
Since some cinemas (often smaller ones) still hand out paper-based tickets, the Backend needs to implement a endpoint which allows tracking the ticket numbers that have been issued.
This endpoint needs to be increment only and shall only be resettable if a transaction containing the tickets is cancelled afterwards.

**Comment by dr4hcu5-jan** [comment]
# Required Tasks

- [ ] Extend Item Objects to allow setting items as ticket/containing a ticket
- [ ] Create API Endpoint to receive the currently issued ticket number
- [ ] Create API Endpoint to reverse a transaction
